import type { Metadata } from "next";
import { Prompt, Poppins } from "next/font/google";
import "../themes/globals.css"; 

const prompt = Prompt({
  subsets: ['thai', 'latin'],
  weight: ['600'],
  variable: '--font-prompt',
  display: 'swap',
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}