import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import "./globals.css";;
import "primereact/resources/themes/lara-light-blue/theme.css"; 
import "primereact/resources/primereact.min.css";               
import "primeicons/primeicons.css";                             

const prompt = Prompt({
  variable: '--font-prompt',
  display: 'swap',
  subsets: ['thai'],
  weight: ['600'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${prompt.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
