import type { Metadata } from "next";
import { Prompt, Poppins } from "next/font/google";            

const prompt = Prompt({
  variable: '--font-prompt',
  display: 'swap',
  subsets: ['thai'],
  weight: ['600'],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={`${prompt.variable} ${poppins.variable} antialiased`}>
          {children}
        </body>
    </html>
  );
}
